### ISSUE TITLE
Json数据太多之后打印不全

### ISSUE THREAD

**Issue by zhoujia456888** [DesignQu/Logg#1]
我项目的json数据在格式化之后大概有500多行（长度超过了1024*3）。用Logg.json打印不全，只显示一部分。

**Comment by RockyQu** [comment]
@zhoujia456888 那得用其他的了，用i,w,d,e这些的应该行，Logg.json就是代格式化的，要是数据太多了格式化也太长了没法看了，太大的我一般是复制出来，在http://www.bejson.com/ 这里看方便些
